DSU24/Models/ApiResponse.cs
using System.Net;

namespace DSU24.Models
{
    public class ApiResponse<T>
    {
        public T Data { get; set; }
        public HttpResponseMessage Response { get; set; }
        public string ErrorMessage { get; set; }
        public HttpStatusCode StatusCode { get; internal set; }
        public bool IsSuccessful => string.IsNullOrEmpty(ErrorMessage);
    }
}

DSU24/Models/Data/SportDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace DSU24.Models.Data
{
    public class SportDbContext : DbContext
    {
        public DbSet<Sport> Sports { get; set; }
        public DbSet<Season> Seasons { get; set; }

        public SportDbContext(DbContextOptions<SportDbContext> options) : base(options) { }

    }
}

DSU24/Models/DisplaySportViewModel.cs
namespace DSU24.Models
{
    public class DisplaySportViewModel
    {
        public decimal Price { get; set; }
        public string Name { get; set; }
        public IEnumerable<string> Sports { get; set; }
        // visa bara de saker som ska vara publika
        public DisplaySportViewModel(Sport sport)
        {
                Price = sport.Price;
        }
        public DisplaySportViewModel()
        {
            Sports = new List<string>() { "Golf", "Handboll", "Klättring" };
        }
    }
}

DSU24/Models/DisplayWeatherForecastViewModel.cs
namespace DSU24.Models
{
    public class DisplayWeatherForecastViewModel
    {
        public double Temperature { get; set; }
        public DisplayWeatherForecastViewModel(WeatherForecastDto weatherForecastDto)
        {
            Temperature = -19.5;
        }
    }
}

DSU24/Models/Dtos/CoordinatesDto.cs
namespace DSU24.Models.Dtos
{
    public class CoordinatesDto
    {
        public double[] Coordinates { get; set; }
    }
}

DSU24/Models/Dtos/GeometryDto.cs
using Microsoft.Extensions.Primitives;

namespace DSU24.Models.Dtos
{
    public class GeometryDto
    {
        public string Type { get; set; }
        public List<List<double>> Coordinates { get; set; }
    }
}

DSU24/Models/ErrorViewModel.cs
namespace DSU24.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DSU24/Models/NewSportViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace DSU24.Models
{
    public class NewSportViewModel
    {
        [Required(ErrorMessage ="Du måste fylla i namnet")]
        public string Name { get; set; }

        public int SelectedCategory { get; set; }
        public List<SelectListItem> Categories { get; set; }

        public NewSportViewModel()
        {
            Categories = new List<SelectListItem>
            {
                new SelectListItem{Value="1", Text="Vintersport"},
                new SelectListItem{Value="2", Text="Sommarsport"},
            };
        }
    }
}

DSU24/Models/Season.cs
namespace DSU24.Models
{
    public class Season
    {
        public int Id { get; set; }
        public string Name { get; set; }

        // navigation property
        public virtual ICollection<Sport> Sports { get; set; }
    }
}

DSU24/Models/Sport.cs
using System.ComponentModel.DataAnnotations;

namespace DSU24.Models
{
    public class Sport
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal SecretCost { get; set; }
        public decimal Price { get; set; }

        // navigation property
        public virtual Season? Season{ get; set; } // =  nullable
    }
}

DSU24/Models/WeatherForecastDto.cs
using DSU24.Models.Dtos;

namespace DSU24.Models
{
    public class WeatherForecastDto
    {
        public DateTime ApprovedTime { get; set; }
        public GeometryDto Geometry { get; set; }
    }
}

DSU24/Controllers/HomeController.cs
using DSU24.DAL;
using DSU24.Infrastructure;
using DSU24.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace DSU24.Controllers
{
    public class HomeController : Controller
    {
        private readonly IApiRepository _repo;
        private readonly IDbRepository _dbRepository;
        private readonly ILogger<HomeController> _logger;
        private void Erik(string message="hej")
        {

        }
        public HomeController(ILogger<HomeController> logger, IApiRepository apiRepository, IDbRepository dbRepository)
        {
            _repo = apiRepository;
            _dbRepository = dbRepository;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var model = _repo.GetThunder();
            //Sport sport = new Sport();
            //sport.Name="Klättring";
            //sport.Price = 135;
            //sport = await _dbRepository.AddSportAsync(sport);

            var sports = await _dbRepository.GetSportsAsync();
            var seasons = await _dbRepository.GetSeasonsAsync();
            //string apiUrl = "https://opendata-download-metfcst.smhi.se/api/category/pmp3g/version/2/geotype/point/lon/14.651646/lat/63.177673/data.json";
            //var response =await ApiEngine.Fetch<WeatherForecastDto>(apiUrl); // hämta från api
            //var model = new DisplayWeatherForecastViewModel(response.Data);
            return View();
        }

        public IActionResult Privacy() //action control
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DSU24/Controllers/SportController.cs
using DSU24.Models;
using Microsoft.AspNetCore.Mvc;

namespace DSU24.Controllers
{
    public class SportController : Controller
    {
        //[Route("/erik")]
        public IActionResult Index()
        {
            // hämta data från api
            // manipulera data
            // lägg på annan info
            // skicka till användern i vyn
            var model = new DisplaySportViewModel();
            // cors
            model.Name = "Cykel";
            return View(model);
        }
        //[Route("sport/{id}")]
        //public IActionResult Index(int id)
        //{
        //    // hämta data från api
        //    // manipulera data
        //    // lägg på annan info
        //    // skicka till användern i vyn
        //    var model = new DisplaySportViewModel();
        //    // cors
        //    model.Name = "Cykel";
        //    return View(model);
        //}

      
        public IActionResult New()
        {
            var model = new NewSportViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult New(NewSportViewModel model)
        {
            if (ModelState.IsValid)
            {
                // spara
                return Content("Din post har sparats");
            }
            return View(model);
        }
    }
}

DSU24/Controllers/WeatherViewComponent.cs
using DSU24.Infrastructure;
using DSU24.Models;
using Microsoft.AspNetCore.Mvc;

namespace DSU24.Controllers
{
    public class WeatherViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            string apiUrl = "https://opendata-download-metfcst.smhi.se/api/category/pmp3g/version/2/geotype/point/lon/14.651646/lat/63.177673/data.json";
            var response = await ApiEngine.Fetch<WeatherForecastDto>(apiUrl); // hämta från api
            var model = new DisplayWeatherForecastViewModel(response.Data);
            return View(model);
        }
    }
}

DSU24/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div>@await Component.InvokeAsync("Weather")</div>

DSU24/Views/Shared/Components/Weather/Default.cshtml
@model DSU24.Models.DisplayWeatherForecastViewModel

<h3>@Model.Temperature</h3>

DSU24/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DSU24</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DSU24.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DSU24</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sport" asp-action="Index">Sport</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DSU24 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DSU24/Views/Sport/Index.cshtml
@model DSU24.Models.DisplaySportViewModel;

@{
    ViewData["Title"] = "Sport och lek";
}

<h2>En sportsida</h2>

@foreach(var sport in Model.Sports)
{
    <h3>@sport</h3>
}

DSU24/Views/Sport/New.cshtml
@model DSU24.Models.NewSportViewModel;

<form asp-action="New" asp-controller="sport" method="post">
    @Html.DropDownListFor(c => c.SelectedCategory, Model.Categories, "Välj en kategori")
    <div>
        <label for="Name">Name:</label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
<button type="submit">Spara</button>
</form>